/*
 * Copyright 2025 JSerde
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jserde.javacc;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.io.IOException;
import java.io.Reader;

/**
 * {@link CharStream} on a {@link Reader}.
 *
 * @author Laurent Pireyn
 */
// TODO #optimize: This class comes from the boilerplate classes generated by JavaCC and can probably be optimized
@SuppressWarnings("checkstyle:MethodName")
@SuppressFBWarnings("NM_METHOD_NAMING_CONVENTION")
public final class ReaderCharStream implements CharStream {
    private static final int DEFAULT_BUFFER_SIZE = 5 * 1024;
    private static final int BUFFER_INCREMENT = 5 * 1024;

    private final Reader reader;

    private char[] buffer;
    private int bufferSize;
    private int bufferAvailable;
    private int bufferIndex = -1;
    private int maxNextCharIndex;
    private int inBuffer;
    private int beginIndex;
    private int line = 1;
    private int column;
    private int[] bufferLine;
    private int[] bufferColumn;
    private boolean prevCharIsLf;
    private boolean prevCharIsCr;

    public ReaderCharStream(Reader reader, int bufferSize) {
        this.reader = reader;
        this.bufferSize = bufferSize;
        bufferAvailable = bufferSize;
        buffer = new char[bufferSize];
        bufferLine = new int[bufferSize];
        bufferColumn = new int[bufferSize];
    }

    public ReaderCharStream(Reader reader) {
        this(reader, DEFAULT_BUFFER_SIZE);
    }

    private void expandBuffer(boolean wrapAround) {
        final var buffer = this.buffer;
        final var bufferSize = this.bufferSize;
        final var bufferIndex = this.bufferIndex;
        final var beginIndex = this.beginIndex;
        final var newBuffer = new char[bufferSize + BUFFER_INCREMENT];
        final var newBufferLine = new int[bufferSize + BUFFER_INCREMENT];
        final var newBufferColumn = new int[bufferSize + BUFFER_INCREMENT];
        if (wrapAround) {
            System.arraycopy(buffer, beginIndex, newBuffer, 0, bufferSize - beginIndex);
            System.arraycopy(buffer, 0, newBuffer, bufferSize - beginIndex, bufferIndex);
            this.buffer = newBuffer;
            System.arraycopy(bufferLine, beginIndex, newBufferLine, 0, bufferSize - beginIndex);
            System.arraycopy(bufferLine, 0, newBufferLine, bufferSize - beginIndex, bufferIndex);
            bufferLine = newBufferLine;
            System.arraycopy(bufferColumn, beginIndex, newBufferColumn, 0, bufferSize - beginIndex);
            System.arraycopy(bufferColumn, 0, newBufferColumn, bufferSize - beginIndex, bufferIndex);
            bufferColumn = newBufferColumn;
            this.bufferIndex += bufferSize - beginIndex;
        } else {
            System.arraycopy(buffer, beginIndex, newBuffer, 0, bufferSize - beginIndex);
            this.buffer = newBuffer;
            System.arraycopy(bufferLine, beginIndex, newBufferLine, 0, bufferSize - beginIndex);
            bufferLine = newBufferLine;
            System.arraycopy(bufferColumn, beginIndex, newBufferColumn, 0, bufferSize - beginIndex);
            bufferColumn = newBufferColumn;
            this.bufferIndex -= beginIndex;
        }
        maxNextCharIndex = bufferIndex;
        this.bufferSize += BUFFER_INCREMENT;
        bufferAvailable = bufferSize;
        this.beginIndex = 0;
    }

    private void fillBuffer() throws IOException {
        final var bufferSize = this.bufferSize;
        final var bufferAvailable = this.bufferAvailable;
        final var beginIndex = this.beginIndex;
        if (maxNextCharIndex == bufferAvailable) {
            if (bufferAvailable == bufferSize) {
                if (beginIndex > BUFFER_INCREMENT) {
                    bufferIndex = 0;
                    maxNextCharIndex = 0;
                    this.bufferAvailable = beginIndex;
                } else if (beginIndex < 0) {
                    bufferIndex = 0;
                    maxNextCharIndex = 0;
                } else {
                    expandBuffer(false);
                }
            } else if (bufferAvailable > beginIndex) {
                this.bufferAvailable = bufferSize;
            } else if (beginIndex - bufferAvailable < BUFFER_INCREMENT) {
                expandBuffer(true);
            } else {
                this.bufferAvailable = beginIndex;
            }
        }
        try {
            final var count = reader.read(buffer, maxNextCharIndex, bufferAvailable - maxNextCharIndex);
            if (count == -1) {
                // EOF
                throw new IOException();
            } else {
                maxNextCharIndex += count;
            }
        } catch (IOException e) {
            --bufferIndex;
            backup(0);
            if (beginIndex == -1) {
                this.beginIndex = bufferIndex;
            }
            throw e;
        }
    }

    @Override
    public char readChar() throws IOException {
        final var buffer = this.buffer;
        if (inBuffer > 0) {
            --inBuffer;
            ++bufferIndex;
            if (bufferIndex == bufferSize) {
                bufferIndex = 0;
            }
            return buffer[bufferIndex];
        }
        ++bufferIndex;
        final var bufferIndex = this.bufferIndex;
        if (bufferIndex >= maxNextCharIndex) {
            fillBuffer();
        }
        final var c = buffer[bufferIndex];
        ++column;
        if (prevCharIsLf) {
            ++line;
            column = 1;
            prevCharIsLf = false;
        } else if (prevCharIsCr) {
            prevCharIsCr = false;
            if (c == '\n') {
                prevCharIsLf = true;
            } else {
                ++line;
                column = 1;
            }
        }
        if (c == '\n') {
            prevCharIsLf = true;
        } else if (c == '\r') {
            prevCharIsCr = true;
        }
        bufferLine[bufferIndex] = line;
        bufferColumn[bufferIndex] = column;
        return c;
    }

    @Override
    public void backup(int count) {
        inBuffer += count;
        bufferIndex -= count;
        if (bufferIndex < 0) {
            bufferIndex += bufferSize;
        }
    }

    @Override
    public char BeginToken() throws IOException {
        beginIndex = -1;
        final var c = readChar();
        beginIndex = bufferIndex;
        return c;
    }

    @Override
    public String GetImage() {
        final var buffer = this.buffer;
        final var bufferIndex = this.bufferIndex;
        final var beginIndex = this.beginIndex;
        return bufferIndex >= beginIndex
            ? new String(buffer, beginIndex, bufferIndex - beginIndex + 1)
            : new String(buffer, beginIndex, bufferSize - beginIndex) + new String(buffer, 0, bufferIndex + 1);
    }

    @Override
    public char[] GetSuffix(int length) {
        final var buffer = this.buffer;
        final var bufferIndex = this.bufferIndex;
        final var suffix = new char[length];
        if (bufferIndex + 1 >= length) {
            System.arraycopy(buffer, bufferIndex - length + 1, suffix, 0, length);
        } else {
            System.arraycopy(buffer, bufferSize - (length - bufferIndex - 1), suffix, 0, length - bufferIndex - 1);
            System.arraycopy(buffer, 0, suffix, length - bufferIndex - 1, bufferIndex + 1);
        }
        return suffix;
    }

    @Override
    public int getBeginLine() {
        return bufferLine[beginIndex];
    }

    @Override
    public int getBeginColumn() {
        return bufferColumn[beginIndex];
    }

    @Override
    public int getEndLine() {
        return bufferLine[bufferIndex];
    }

    @Override
    public int getEndColumn() {
        return bufferColumn[bufferIndex];
    }

    @Override
    public void close() throws IOException {
        reader.close();
    }
}
