/*
 * Copyright 2025 JSerde
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package jserde.javacc;

import java.io.Serial;
import jserde.core.util.StringUtils;
import org.jspecify.annotations.Nullable;

/**
 * {@link RuntimeException} thrown by token managers generated by JavaCC.
 *
 * @author Laurent Pireyn
 */
public class TokenMgrException extends RuntimeException {
    // NOTE: These are used by the token manager and cannot be modified
    public static final int LEXICAL_ERROR = 0;
    public static final int STATIC_LEXER_ERROR = 1;
    public static final int INVALID_LEXICAL_STATE = 2;
    public static final int LOOP_DETECTED = 3;

    @Serial
    private static final long serialVersionUID = 1L;

    // NOTE: This is only used by the token manager when debug is enabled
    public static String addEscapes(String string) {
        return StringUtils.javaEscaped(string);
    }

    private static @Nullable String createMessage(
        int reason,
        int state,
        int errorLine,
        int errorColumn,
        @Nullable String errorAfter,
        int ch
    ) {
        return switch (reason) {
            case LEXICAL_ERROR -> createLexicalErrorMessage(state, errorLine, errorColumn, errorAfter, ch);
            case INVALID_LEXICAL_STATE -> createInvalidLexicalStateMessage(state);
            // TODO: Create messages for the other reasons
            default -> null;
        };
    }

    private static String createLexicalErrorMessage(
        int state,
        int errorLine,
        int errorColumn,
        @Nullable String errorAfter,
        int ch
    ) {
        final var builder = new StringBuilder(200);
        builder.append("Lexical error")
            .append(" at line ").append(errorLine)
            .append(", column ").append(errorColumn)
            .append("; encountered ").append(StringUtils.charDescription(ch));
        if (errorAfter != null && !errorAfter.isEmpty()) {
            builder.append(" after prefix \"").append(StringUtils.javaEscaped(errorAfter)).append('"');
        }
        if (state != 0) {
            builder.append(" in lexical state ").append(state);
        }
        return builder.toString();
    }

    private static String createInvalidLexicalStateMessage(int state) {
        return "Invalid lexical state: " + state;
    }

    private final int reason;

    // NOTE: This is used by the token manager and cannot be modified
    public TokenMgrException(@Nullable String message, int reason) {
        super(message);
        this.reason = reason;
    }

    // NOTE: This is used by the token manager and cannot be modified
    public TokenMgrException(
        @SuppressWarnings("unused")
        boolean eof,
        int state,
        int errorLine,
        int errorColumn,
        @Nullable String errorAfter,
        int ch,
        int reason
    ) {
        this(
            createMessage(reason, state, errorLine, errorColumn, errorAfter, ch),
            reason
        );
    }

    public final int getReason() {
        return reason;
    }
}
