name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build project
        run: ./gradlew build
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            jserde-*/build/test-results/test/TEST-*.xml
            jserde-*/build/test-results/jsonTestSuite/TEST-*.xml
          comment_mode: off

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v4
